# ============================================================
# APPLICATION
# ============================================================
spring.application.name=filemanager-backend
server.port=8080


# BASE DE DONNÉES POSTGRESQL

# les données en local :

# URL locale : jdbc:postgresql://localhost:5432/filemanagement
# username : postgres
# Password: root

# les données à distance :

spring.datasource.url=jdbc:postgresql://ep-flat-forest-atq3aib3-pooler.c-9.us-east-1.aws.neon.tech/filemanagment_db?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_VRpxdlbW60qw
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# JWT
# Clé secrète Base64 (min 256 bits pour HS256) — CHANGEZ EN PROD
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000


# UPLOAD DE FICHIERS
# Dossier de stockage des PDF (chemin absolu ou relatif)
app.upload.dir=/var/data/uploads

# Taille max d'un fichier : 20 Mo
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# CORS (adapter à l'URL de votre frontend React)
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000
